after_success: npm run coverage
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
install: rm package-lock.json && npm install
language: node_js
node_js: stable
script: npm test
sudo: false
